#!/usr/bin/python3

"""http://archive.moe/a/thread/112792840/#112792840"""
import moesearch
import re
import sys
S = sys.argv

retrieve_post_num = lambda url: re.findall("\d+$", url)[0]
retrieve_board = lambda url: re.findall("/(\w+)/thread", url)[0]

#print( retrieve_post_num(S[1]) )
#print( retrieve_board(S[1]) )

print(moesearch.post(retrieve_board(S[1]), retrieve_post_num(S[1])))
